### ISSUE TITLE
Handle detailed postal codes for Great Britain

### ISSUE THREAD

**Issue by rth** [symerio/pgeocode#4]
The GB dataset for Great Britain only includes [outwards codes](https://en.wikipedia.org/wiki/Postcodes_in_the_United_Kingdom#Outward_code) (i.e. only first 3 letters). The full dataset is included in `GB_full`, but currently this fails to load,
```
>>> import pgeocode
>>> dist = pgeocode.GeoDistance('GB_full')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rth/src/pgeocode/pgeocode.py", line 174, in __init__
    super(GeoDistance, self).__init__(country)
  File "/home/rth/src/pgeocode/pgeocode.py", line 49, in __init__
    .format(country))
ValueError: country=GB_FULL is not a known country code. See the README for a list of supported countries
```

**Comment by amarchin** [comment]
Hi, I was looking for a package like `pgeocode`. Unfortunately I need the GB_full dataset so I open a PR to address  this issue: https://github.com/symerio/pgeocode/pull/18

Let me know if you think it is acceptable :) 

Thank you for the package!

**Comment by alvise1988** [comment]
Hello @rth ,

First of all, thanks for the useful package!

I would be looking exactly for this feature and most of the work seems to have been done already. Is there any particular reason why the PR was never merged?

Thanks

**Comment by martijnschouten** [comment]
I updated the package to support the full list of postal codes of the Netherlands and Great Brittain. See d32dace3a03647ffc72a491ae3ab441533d86b6f
